#
# Copyright (C) 2020 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-bridge"
version = "0.1.0"
authors = ["Signal Messenger LLC"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
attest = { path = "../../attest" }
device-transfer = { path = "../../device-transfer" }
libsignal-bridge-macros = { path = "macros" }
libsignal-bridge-types = { path = "types" }
libsignal-core = { path = "../../core" }
libsignal-message-backup = { path = "../../message-backup" }
libsignal-net = { path = "../../net" }
libsignal-protocol = { path = "../../protocol" }
signal-crypto = { path = "../../crypto" }
signal-media = { path = "../../media", optional = true }
signal-pin = { path = "../../pin" }
usernames = { path = "../../usernames" }
zkgroup = { path = "../../zkgroup" }

aes-gcm-siv = "0.11.1"
base64 = { workspace = true }
bincode = { workspace = true }
futures-util = { workspace = true }
hkdf = { workspace = true }
hmac = { workspace = true }
http = { workspace = true }
log = { workspace = true }
nonzero_ext = { workspace = true }
paste = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
scopeguard = { workspace = true }
sha2 = { workspace = true }
static_assertions = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
uuid = { workspace = true }

# Enable this for all libsignal app language libraries
subtle = { workspace = true, features = ["core_hint_black_box"] }

jni = { workspace = true, optional = true }
linkme = { workspace = true, optional = true }
neon = { workspace = true, optional = true, default-features = false, features = ["napi-6"] }
strum = { workspace = true, features = ["derive"] }

[dev-dependencies]
assert_matches = { workspace = true }
test-case = { workspace = true }
testing_logger = { workspace = true }
tokio = { workspace = true, features = ["test-util", "time", "macros"] }

[features]
ffi = ["libsignal-bridge-types/ffi"]
jni = ["dep:jni", "libsignal-bridge-types/jni"]
node = ["neon", "linkme", "libsignal-bridge-types/node"]
signal-media = ["dep:signal-media", "libsignal-bridge-types/signal-media"]
