#
# Copyright (C) 2020-2021 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-node"
version = "0.58.3"
authors = ["Signal Messenger LLC"]
license = "AGPL-3.0-only"
edition = "2021"

[lib]
name = "signal_node"
crate-type = ["cdylib"]

[dependencies]
libsignal-bridge = { path = "../shared", features = ["node", "signal-media"] }
libsignal-bridge-testing = { path = "../shared/testing", features = ["node", "signal-media"] }
libsignal-protocol = { path = "../../protocol" }

futures = { workspace = true }
log = { workspace = true }
log-panics = { workspace = true, features = ["with-backtrace"] }
minidump = { version = "0.21.2", default-features = false }
minidump-processor = { version = "0.21.2", default-features = false }
minidump-unwind = { version = "0.21.2", default-features = false }
neon = { version = "1.0.0", default-features = false, features = ["napi-6"] }

[build-dependencies]
# cmake 0.1.49 breaks no-toolchain Windows cross-compilation using Visual Studio
# https://github.com/rust-lang/cmake-rs/pull/158#issuecomment-1544695163
cmake = ">= 0.1, < 0.1.49"
