#
# Copyright (C) 2024 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "libsignal-jni-testing"
version = "0.58.3"
authors = ["Signal Messenger LLC"]
edition = "2021"
license = "AGPL-3.0-only"

[lib]
name = "signal_jni_testing"
crate-type = ["cdylib"]

[dependencies]
libsignal-bridge-testing = { path = "../../shared/testing", features = ["jni"] }
libsignal-bridge-types = { path = "../../shared/types", features = ["jni"] }

jni = { workspace = true }
log = { workspace = true }
