[package]
name = "libsignal-net"
version = "0.1.0"
edition = "2021"
authors = ["Signal Messenger LLC"]
license = "AGPL-3.0-only"

[features]
test-util = []

[dependencies]
attest = { path = "../attest" }
libsignal-core = { path = "../core" }
libsignal-net-infra = { path = "./infra" }
libsignal-protocol = { path = "../protocol" }
libsignal-svr3 = { path = "../svr3" }

async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bytes = "1.4.0"
const-str = { version = "0.5.6", features = ["std"] }
derive-where = { workspace = true }
displaydoc = { workspace = true }
either = "1.10.0"
futures-util = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
http = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
nonzero_ext = { workspace = true }
num_enum = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
snow = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "macros"] }
tokio-boring-signal = { workspace = true }
tokio-stream = { workspace = true }
tokio-tungstenite = "0.23.0"
tungstenite = { version = "0.23.0", features = ["url"] }
url = "2.4.1"
uuid = { workspace = true }
zerocopy = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
libsignal-net-infra = { path = "./infra", features = ["test-util"] }
clap = { workspace = true, features = ["derive"] }
colored = "2.1"
env_logger = { workspace = true }
hex-literal = { workspace = true }
proptest = { workspace = true }
proptest-state-machine = "0.1.0"
snow = { workspace = true, features = ["default-resolver"] }
test-case = { workspace = true }
test-log = "0.2.16"
tokio = { workspace = true, features = [
    "test-util",
    "io-std",
    "rt-multi-thread",
] }
warp = { version = "0.3.6", features = ["tls"] }

[[example]]
name = "svr3_prop_test"
required-features = ["test-util"]

[[example]]
name = "chat_smoke_test"
required-features = ["test-util"]

[[test]]
name = "svr3"
required-features = ["test-util"]

[[test]]
name = "svr3_migration"
required-features = ["test-util"]
