[package]
name = "libsignal-net-infra"
version = "0.1.0"
edition = "2021"
authors = ["Signal Messenger LLC"]
license = "AGPL-3.0-only"

[features]
test-util = ["dep:warp", "snow/default-resolver"]

[dependencies]
attest = { path = "../../attest" }

async-trait = { workspace = true }
base64 = { workspace = true }
bitstream-io = "1.10.0"
boring-signal = { workspace = true }
bytes = "1.4.0"
const-str = { version = "0.5.6", features = ["std"] }
derive-where = { workspace = true }
displaydoc = { workspace = true }
either = "1.10.0"
futures-util = { workspace = true }
http = { workspace = true }
http-body-util = "0.1.1"
hyper = { version = "1.3.1", features = ["http2", "client"] }
hyper-util = { version = "0.1.3", features = ["tokio"] }
indexmap = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
nonzero_ext = { workspace = true }
pin-project = "1.1.5"
prost = { workspace = true }
rustls = { version = "0.23.4", default-features = false, features = ["ring", "std", "tls12"] }
rustls-platform-verifier = { workspace = true }
snow = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "macros"] }
tokio-boring-signal = { workspace = true }
tokio-socks = "0.5.2"
tokio-tungstenite = "0.23.0"
tokio-util = "0.7.9"
tungstenite = { version = "0.23.0", features = ["url"] }
url = "2.4.1"
warp = { version = "0.3.6", features = ["tls"], optional = true }

[dev-dependencies]
assert_matches = { workspace = true }
env_logger = { workspace = true }
hickory-proto = "0.24.1"
lazy_static = { workspace = true }
pretty_assertions = { workspace = true }
rcgen = "0.13.0"
snow = { workspace = true, features = ["default-resolver"] }
socks5-server = "0.10.1"
test-case = { workspace = true }
tls-parser = "0.11.0"
tokio = { workspace = true, features = [
    "test-util",
    "io-std",
    "rt-multi-thread",
] }
tokio-stream = { workspace = true }
warp = { version = "0.3.6", features = ["tls"] }
