name: Lints
# This is in a separate job because we have shell scripts scattered across all our targets,
# *and* some of them have common dependencies.

on:
  push:
    branches: [ main ]
    paths: ['**/*.sh', '**/*.py', '.github/workflows/lints.yml']
  pull_request:
    paths: ['**/*.sh', '**/*.py', '.github/workflows/lints.yml']

jobs:
  lint:
    name: Check helper scripts

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        submodules: recursive
    - run: sudo apt-get update && sudo apt-get install python3-flake8 python3-mypy
    - run: shellcheck **/*.sh bin/verify_duplicate_crates bin/adb-run-test
    - run: python3 -m flake8 .
    - run: python3 -m mypy . --python-version 3.9 --strict
